- name: Create the Nautobot System User
  ansible.builtin.user:
    name: nautobot
    system: True
    create_home: True
    skeleton: "{{nautobot_user_home}}"
    shell: /bin/bash
    groups: nautobot, sudo
    append: yes
  become: True

- name: Create Virtual Environment
  become: yes
  become_user: nautobot
  pip:
    name: nautobot
    virtualenv: /opt/nautobot
    virtualenv_python: python"{{python_version}}"


- name: Update Naubotbot .bashrc
  become: yes
  become_user: nautobot
  ansible.builtin.lineinfile:
    path: ~nautobot/.bashrc
    line: export NAUTOBOT_ROOT=/opt/nautobot
    state: present

- name: install and upgrade nautobot
  become: yes
  become_user: nautobot
  pip: 
    name: nautobot
    state: latest
    virtualenv: /opt/nautobot

- name: initialize your config
  command: nautobot-server init
  become: yes
  become_user: nautobot
  register: tmp_user

- name: show user
  debug:
    var: tmp_user


# - name: Update the Nautobot .bashrc
#   become: yes
#   ansible.builtin.command: echo "export NAUTOBOT_ROOT=/opt/nautobot" | tee -a ~nautobot/.bashrc  

# - name: Debug which pip
#   debug:
#     ansible.builtin.command: which pip3





      # - name: ensure apache is at the latest version
      #   yum:
      #     name: httpd
      #     state: latest
      # - name: ensure apache is running
      #   service:
      #     name: httpd
      #     state: started